plugins {
    id 'java-library'
    id 'org.springframework.boot'
    id 'io.spring.dependency-management'
    id 'java-test-fixtures'
}

dependencies {
    implementation project(":common")
    api "org.springframework.boot:spring-boot-starter-kafka"
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation "org.springframework.kafka:spring-kafka-test"
}
